# | Input Devices |
# Configure your input devices here. | https://mangowm.github.io/docs/configuration/input

# xkb_rules_layout = us

# If you want to disable pointer acceleration, uncomment the lines below.
# accel_profile = 1
# accel_speed = 0.2
#

# Keyboard
repeat_delay=500
repeat_rate=40
numlockon=1

# Mouse
mouse_natural_scrolling=1
mouse_accel_profile=1
mouse_accel_speed=0.5

# Trackpad
trackpad_natural_scrolling=1
trackpad_accel_profile=1
trackpad_accel_speed=0.5
trackpad_scroll_factor=1.2
tap_to_click=1
tap_and_drag=1
trackpad_disable_while_typing=1

