# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x111416ff
bordercolor = 0x8b9198ff
dropcolor = 0x9dccf180
splitcolor = 0xe1b9edff
focuscolor = 0x9dccf1ff
maximizescreencolor = 0xb7c9d9ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe1b9edff
globalcolor = 0x074463ff
overlaycolor = 0x3a4b58ff
jump_label_decorate_fg_color = 0xe2e2e5ff
jump_label_decorate_bg_color = 0x282a2dff
jump_label_decorate_focus_fg_color = 0x00344eff
jump_label_decorate_focus_bg_color = 0x9dccf1ff
jump_label_decorate_border_color = 0x8b9198ff
group_bar_decorate_fg_color = 0xe2e2e5ff
group_bar_decorate_bg_color = 0x282a2dff
group_bar_decorate_focus_fg_color = 0x00344eff
group_bar_decorate_focus_bg_color = 0x9dccf1ff
group_bar_decorate_border_color = 0x8b9198ff
