# Noctalia Theme for Mango
# Generated automatically by Noctalia

rootcolor = 0x200f0cff
bordercolor = 0xae8881ff
dropcolor = 0xffb4a880
splitcolor = 0xfbbb53ff
focuscolor = 0xffb4a8ff
maximizescreencolor = 0xffb4a8ff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xfbbb53ff
globalcolor = 0xff5540ff
overlaycolor = 0x8f1a0fff
jump_label_decorate_fg_color = 0xfedbd5ff
jump_label_decorate_bg_color = 0x392521ff
jump_label_decorate_focus_fg_color = 0x680100ff
jump_label_decorate_focus_bg_color = 0xffb4a8ff
jump_label_decorate_border_color = 0xae8881ff
group_bar_decorate_fg_color = 0xfedbd5ff
group_bar_decorate_bg_color = 0x392521ff
group_bar_decorate_focus_fg_color = 0x680100ff
group_bar_decorate_focus_bg_color = 0xffb4a8ff
group_bar_decorate_border_color = 0xae8881ff
