include=/home/gskumar/.config/fuzzel/themes/noctalia

[main]
# Font styling (adjust the size and font family to suit your setup)
font=JetBrains Mono Nerd Font Propo:size=13
dpi-aware=auto

# Prompt icon or text
prompt="➡️  "
layer=overlay

# Layout dimensions
width=40
lines=10
horizontal-pad=25
vertical-pad=20
inner-pad=12

# Behavior
terminal=foot -e # Replace with your preferred terminal emulator (e.g., alacritty, kitty)
show-actions=true
icon-theme=Papirus-Dark # Ensure you have an icon theme installed, or use your system default

[border]
width=2
radius=8

















