
"Apps" "Rofi App launcher" "Shows Apps" "$HOME/.config/scripts/show-apps-rofi.sh" "gui"
"Apps" "WebApps" "Launches webapps using brave origin" "$HOME/.config/scripts/webapps-launcher.sh" "gui"

"Utility" "Nvidia Services" "Manages services" "$HOME/.config/scripts/nvidia-services.sh" "tui"
"Utility" "GDU" "disk usage analyzer"  "gdu /" "tui"
"Utility" "Terminal file manager" "Yazi file manager" "yazi" "tui"
"Utility" "System Info" "complete info using fastfetch"  "fastfetch -c all" "cli"
"Utility" "System Monitor" "monitors resources"  "btop --force-utf" "tui"
"Utility" "File Encryption" "Vault manager using gocryptfs" "$HOME/.config/scripts/gocryptfs-tui.sh" "tui"
"Utility" "Screenshot CLI" "cli for screenshot keybinds usage" "$HOME/.config/scripts/screenshot-cli.sh" "cli"
"Utility" "Fuzzy search" "file & text search" "$HOME/.config/scripts/fzf-search.sh" "cli"
"Utility" "Quick Download" "Simple downloader" "$HOME/.config/scripts/quick-download.sh" "tui"
"Utility" "Hyprland Keybinds" "shortcut keys" "$HOME/.config/scripts/hypr-binds.sh" "gui"

"Productivity" "Quick Note" "for cli & keybinds" "$HOME/.config/scripts/quicknote.sh" "tui"
"Productivity" "Quick Reminder" "for cli & keybinds" "$HOME/.config/scripts/quickreminder.sh" "tui"
"Productivity" "Quick Todo" "for cli & keybinds" "$HOME/.config/scripts/quicktodo.sh" "tui"
"Productivity" "View Quick Notes" "for cli & keybinds" "$HOME/.config/scripts/view-notes.sh" "tui"
"Productivity" "Integrated Note Taker" "quicknotes + markdown notetaker" "$HOME/.config/scripts/integrated-notetaker.sh" "tui"
"Productivity" "Routine Tracker" "Daily Habit tracker" "$HOME/.config/scripts/routine-tui.sh" "tui"
"Productivity" "Quick Timers" "timers, stopwatch, pomo .." "$HOME/.config/scripts/quick-timers.sh" "tui"

"Network" "Cloudflare WARP" "Manages WARP" "$HOME/.config/scripts/warp-manager.sh" "tui"
"Network" "Cloudflare WARP Toggle" "Toggles WARP" "$HOME/.config/scripts/warp-toggle.sh" "cli"
"Network" "DNS switch" "dns options" "$HOME/.config/scripts/dns-switch.sh"  "tui"
"Network" "Network manager" "Nmtui launcher" "nmtui"  "tui"

"Media" "Youtube Downloader (rust)" "yt-dlp menu" "ytdl-rust" "tui"
"Media" "Youtube Downloader" "yt-dlp menu" "$HOME/.config/scripts/yt-dlp-menu.sh" "tui"

"Power" "Power menu" "Rofi based power menu" "$HOME/.config/scripts/rofi-power.sh" "gui"
"Power" "Lenovo Power modes" "Battery cap 60% ON/OFF" "$HOME/.config/scripts/lenovo-battery-modes.sh" "tui"
"Power" "GPU manager" "Supergfxctl management" "$HOME/.config/scripts/gfx-manager.sh" "tui"


